apiVersion: apps/v1
kind: Deployment
metadata:
  name: roombook-api
  namespace: roombook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roombook-api
  template:
    metadata:
      labels:
        app: roombook-api
    spec:
      containers:
        - name: roombook-api
          image: cr.yandex/crp6isv0h7lq8bnroc41/roombook-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: roombook-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: roombook-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: roombook-secret
                  key: DB_PASSWORD
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: roombook-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: roombook-secret
                  key: JWT_REFRESH_SECRET
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U $POSTGRES_USER; do
                echo "Waiting for Postgres..."
                sleep 5
              done
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: roombook-secret
                  key: DB_USERNAME