apiVersion: v1
kind: Service
metadata:
  name: roombook-api
  namespace: roombook
spec:
  selector:
    app: roombook-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer