apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Сбор метрик с backend-приложения напрямую по DNS имени Kubernetes сервиса
      - job_name: 'ktor-backend'
        metrics_path: /metrics
        static_configs:
          - targets: ['roombook-api.roombook.svc.cluster.local:8080']