apiVersion: v1
kind: Secret
metadata:
  name: roombook-secret
  namespace: roombook
type: Opaque
stringData:
  DB_NAME: roombook
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_URL: jdbc:postgresql://postgres:5432/roombook
  JWT_ACCESS_SECRET: access_secret
  JWT_REFRESH_SECRET: refresh_secret